### ISSUE TITLE
Keywords as Foriegn key

### ISSUE THREAD

**Issue by doaa-altarawy** [MolSSI/QCFractal#160]
Use `Keywords` are `ReferenceField` instead of a `StringField` (better validation). Also, why not also use this ReferenceField in Procedures.

Finally, I think the `Keywords` table doesn't need the program field as it can simply be included when creating the `hash_index` itself.

**Comment by dgasmith** [comment]
Agreed on Keywords as ReferenceField. Procedures becomes more difficult as each procedure will use the ReferenceField in a different way. We currently subclass this correctly with ME so we should able to make it work however.

The reason I originally left `program` is that I was toying with catching if the execution program and Keyword program were different we could potentially catch errors. Not sure if this is all that realistic however. I do think the subclassing is useful where `KeywordSet.values` hold the actual keywords so that we can add creation data, comments, provenance, etc.
