### ISSUE TITLE
qcfractal-server stop

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#355]
**Is your feature request related to a problem? Please describe.**
I am writing quickstart setup documentation for qcfractal-server. By and large, the user is instructed to start qcfractal-server in the background and then forget about it (e.g. `nohup qcfractal-server start &`). It would be nice to be able to stop such a qcfractal-server with a simple command (rather than e.g. `pgrep qcfractal-server | xargs kill`).

**Describe the solution you'd like**
A `qcfractal-server stop` command which will safely stop a running qcfractal-server owned by the user.

**Describe alternatives you've considered**
Killing the server with `kill`, or running the server in the foreground, but inside `screen`.

**Comment by dgasmith** [comment]
`qcfractal-server start --fork` is what I have been thinking about. This would recursively call start without the `--fork` kwargs, check to make sure the server booted, disown the process, write a lock file to the fractal base folder, and then shutdown.

The `--fork` option is very Mongo-like while `qcfractal-server start` -> automatic background process would be very PostgreSQL like. Any thoughts on the two different options?

**Comment by mattwelborn** [comment]
Whichever decision is made, I think it makes sense to have the same functionality in `qcfratctal-manager`

**Comment by dgasmith** [comment]
With managers, the `--fork` option seems better as you may run multiple managers per hardware resource. At the same time managers are more likely to be shutdown manually. Maybe managers can work on a per-folder basis and running `start/stop` in a folder with a config would work?

@Lnaden @j-wags any comments?

**Comment by mattwelborn** [comment]
I think that managers won't be so abundant that we can't manage them globally. For example, `qcfractal-manager stop` could check for all running managers. If there is only one manager running, it gets stopped. If there are multiple managers running, it prints out the list of running managers, each with an ID. Then, the user can run `qcfractal-manager stop ID`. (This is similar to the behavior of `screen -x`.

**Comment by dgasmith** [comment]
Big fan of this idea. Likely show the name, queue, start time, and a few other items as well to help people understand which manager to shut down.

**Comment by dgasmith** [comment]
If we implement `start` if there is ever a case where there are multiple managers we must do this to make `stop` work as expected. Each instantiation of a manger would be unique through their UUID, adding in a start time and perhaps the name of the starting config would assist this as well.

**Comment by mattwelborn** [comment]
Reading a little more about this, daemonization is slightly involved. There's a library for it (https://pypi.org/project/python-daemon/), but it seems to be lightly maintained and undocumented.

**Comment by bennybp** [comment]
The way it is currently written, `qcfractal-server` is the process that would be placed in the background. As mentioned, backgrounding itself is tricky, and in the case of multiple servers, fraught with issues and error conditions. The way this is normally done is with a supervisory process/command sitting above (ie, pg_ctl and postgres).

For the MolSSI server, I have a script that starts several `qcfractal-server`s and this is called via a systemd service. I then let systemd handle monitoring and killing all the subprocesses, which is not trivial to do correctly. For now, this is probably the best way to do it for multiple server instances (and integrates nicely with other things, like dependency on postgres and enabling on startup).

There are a few ways we could improve this (rather than a bash script, use python multiprocessing to spawn the pool of processes). But won't likely be a priority for a while unless someone has a more urgent need (and doesn't seem to be too urgent, given this hasn't been touched in > 1 year).

So closing for now
