### ISSUE TITLE
Parsl 0.9.0

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#437]
Parsl's next version will make changes to how manager options like `max_workers` operate and may require that we specify `parsl: provider: cores_per_node: 32`. We will at least need to update the docs, but there may be manager code changes needed as well.

See Parsl/parsl#1341 and Parsl/parsl#1353.

**Comment by dgasmith** [comment]
This should be controlled by the `common: cores_per_worker` effectively?

**Comment by Lnaden** [comment]
Parsl lingo: `max_workers = max_blocks * nodes_per_block * cores_per_node / cores_per_worker`

Our variables: 
* max_blocks = max_workers
* nodes_per_block = 1 
* cores_per_node = cores_per_worker
* cores_per_worker = cores_per_worker / tasks_per_worker

... I think

**Comment by dgasmith** [comment]
I think so, where specifying cores per node less than the maximum number of physical cores per node will allow the cluster schedulers to schedule partial node workers.

**Comment by dgasmith** [comment]
Parsl 0.9 is out.

**Comment by mattwelborn** [comment]
@Lnaden Is there anything we need to do to ensure that new managers don't break?

**Comment by Lnaden** [comment]
I don't think the managers will break. They won't be as efficient until the constructor changes you hashed through go in. I *think* this release also has the start of partial resource hints for some of the schedulers, so it may be worth seeing if we can get those in since you'll need to tinker in code anyways.
