### ISSUE TITLE
TorsionDrive Integrity Error

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#540]
**Describe the bug**
The TorsionDrive id `2703253` is missing several geometry optimizations in its history lookup. 

**To Reproduce**
```python
td = client.query_procedures(id=2703253)[0]
print(len(td.optimization_history["[120]"]), td.minimum_positions["[120]"])
3, 3
```
Where if `minimum_positions` is 3 it must index a `optimization_history` of length 4 (index 3). This indicates that the database join table is missing several geometry optimizations.  This causes several operations to fail when calling the `TorsionDrive` object.

**Expected behavior**
`minimum_positions` must always index `optimization_history`.

**Additional context**
It is unclear if this is a database error, a service class error, or other. Scanning all torsion drives, the only ones affected are:
```python

for chunk in range(10):
    tds = client.query_procedures(procedure="torsiondrive", skip=chunk*1000)
    for td in tds:
        if td.status != "COMPLETE":
            continue
        if all(len(td.optimization_history[k]) > td.minimum_positions[k] for k in td.minimum_positions.keys()):
            continue
        
        print(td.id)

2703616
2703386
2703545
2703343
2703449
2703439
2703546
2703253
```

All of which were last modified July 14th, 2019. Importantly this is not an issue for the ~2500 newer torsion drives and only this set. So I am leaning a bit towards this being a migration bug or state bug rather than a current issue. Still this needs to be tracked down carefully.

**Comment by SimonBoothroyd** [comment]
We also came across this issue today with torsion drive `id=6098580`

**Comment by dotsdl** [comment]
@bennybp can you investigate where drops of optimization history may be happening? Does the source data exist in the database? 

If it doesn't, this may be a case of the manager's submission to the server getting dropped and results not fully making it into the database. This is a problem downstream for fitting efforts, since the resulting optimizations composing the torsiondrive results may not actually give minimum energy results for each dihedral angle.

It may be that the work you're already doing to address non-atomic transactions from the manager -> server -> database will address this. If so, at some point we won't see new cases of this.

The failure mode identified by @SimonBoothroyd above is a loud case, but we have also identified some more silent cases that exhibit similar behavior, where the indices in the `minimum_positions` doesn't match what is actually present in `optimization_history`.

```python
from qcportal import FractalClient
fc = FractalClient()
td = fc.query_procedures(id=6098580)[0]
td.get_final_results()   # IndexError
```

**Comment by bennybp** [comment]
I had tried to fix these, but there are optimizations that I could not find, ad I don't fully trust the calculations anymore.

I have marked the 34 torsiondrive records mentioned above as `invalid`. They will still exist, but hopefully that serves as a signal that the results shouldn't be trusted. This status change is reversible if needed.

Nevertheless, I believe the bug that originally created this issue has been fixed.
