### ISSUE TITLE
Unable to find requested entry.

### ISSUE THREAD

**Issue by njzjz** [MolSSI/QCFractal#662]
**Describe the bug**
I don't know where to report this bug, maybe here?
I cannot fetch ANI-1x dataset from api.qcarchive.molssi.org

**To Reproduce**
```python
import qcportal as ptl
client = ptl.FractalClient(address="api.qcarchive.molssi.org")
ani1x = client.get_collection("dataset", "ANI-1x")
ani1x.get_values()
```
> RuntimeError: Remote view query failed with error message: Unable to find requested entry.

**Expected behavior**
It should get some values?

**Additional context**
I create a colab notebook to reproduce: https://colab.research.google.com/drive/1bXwwYi8tBn8EA6upnkbTHOOeV3IsnuxD?usp=sharing

**Comment by bennybp** [comment]
hm this is a little hard to track down. QCFractal is swallowing any helpful error info, rather than printing it to the logs.

I *believe* this has to do with something I have seen before, where Pandas is returning a list of byte arrays rather than a list of strings for indices. I will see if I can reproduce on a test server

**Comment by bennybp** [comment]
With 0.50, the dataset interface is now completely different. If you are interested, updated documentation is here: https://molssi.github.io/QCFractal

Let us know if you have any other questions
